services:
  seeyarti-redisDB:
    image: 'redis:alpine'
    container_name: seeyarti-redisDB
    command: >
      redis-server --requirepass redispassword --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - seeyarti-development-redisDB:/data
    env_file:
      - ../secrets/.env.development
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "127.0.0.1", "-a", "redispassword", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

networks: 
  seeyarti_development_network:
    driver: bridge

volumes:
  seeyarti-development-redisDB: